//header请求数据；
export const MOVIE_TYPES=[
    {
        id:Math.random()+"1",
        type:'1',
        title:'电视剧',
    },
    {
        id:Math.random()+"2",
        type:'2',
        title:'电影',
    },
    {
        id:Math.random()+"3",
        type:'3',
        title:'动画',
    },
    {
        id:Math.random()+"4",
        type:'4',
        title:'综艺',
    }
]

export const CLASSICAL_TYPES=[
    {
        id:Math.random()+"1",
        type:'1',
        title:'全部',
    },
    {
        id:Math.random()+"2",
        type:'2',
        title:'最爱电影',
    },
    {
        id:Math.random()+"6",
        type:'6',
        title:'最爱电视剧',
    }
]

//轮播图数据;
export const SWIPER_LIST = [
    {
        id:Math.random()+"1",
        picUrl:'http://n.sinaimg.cn/news/transform/700/w1000h500/20180411/d-s3-fyzeyqa3238853.jpg',
        rsId:Math.random()+"11",
        title:"海上牧云姬"
    },
    {
        id:Math.random()+"2",
        picUrl:'http://n.sinaimg.cn/news/transform/700/w1000h500/20180412/I2o6-fyzeyqa8717592.jpg',
        rsId:Math.random()+"22",
        title:"海上牧云姬"
    },
    {
        id:Math.random()+"3",
        picUrl:'http://n.sinaimg.cn/news/transform/700/w1000h500/20180412/JDwj-fyzeyqa8803322.jpg',
        rsId:Math.random()+"33",
        title:"海上牧云姬"
    }
]

export const HOT_SERIES_LIST = [
   {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/transform/700/w1000h500/20180412/I2o6-fyzeyqa8717592.jpg",
        title:"海上牧云姬",
        discription:"九国争霸，灭国统一，谁主沉浮",
        length:"20集",
        flag:1//代表hot
   },
   {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/transform/700/w1000h500/20180412/JDwj-fyzeyqa8803322.jpg",
        title:"海上牧云姬",
        discription:"九国争霸，灭国统一，谁主沉浮",
        length:"20集",
        flag:1//代表hot
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/transform/700/w1000h500/20180411/d-s3-fyzeyqa3238853.jpg",
        title:"海上牧云姬",
        discription:"九国争霸，灭国统一，谁主沉浮",
        length:"20集",
        flag:1//代表hot
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/transform/700/w1000h500/20180412/JDwj-fyzeyqa8803322.jpg",
        title:"海上牧云姬",
        discription:"九国争霸，灭国统一，谁主沉浮",
        length:"20集",
        flag:1//代表hot
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/transform/700/w1000h500/20180411/d-s3-fyzeyqa3238853.jpg",
        title:"海上牧云姬",
        discription:"九国争霸，灭国统一，谁主沉浮",
        length:"20集",
        flag:1//代表hot
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/transform/700/w1000h500/20180412/I2o6-fyzeyqa8717592.jpg",
        title:"海上牧云姬",
        discription:"九国争霸，灭国统一，谁主沉浮",
        length:"20集",
        flag:1//代表hot
    }
]
export const CLASSICAL_SERIES_LIST = [
    {
         id:Math.random()+"1",
         type:1,
         picUrl:"http://n.sinaimg.cn/photo/0/w2000h1200/20180322/XJ_G-fysnevk5977709.jpg",
         title:"新青年",
         discription:"拿起画具，向水面滴入颜料，颜料慢慢漾开",
         length:"20集",
         flag:2//代表经典
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/1_img/upload/3ad618a7/783/w950h633/20180321/J74g-fyskeue2143601.jpg",
        title:"新青年",
        discription:"拿起画具，向水面滴入颜料，颜料慢慢漾开",
        length:"20集",
        flag:2//代表经典
   },
   {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/1_img/upload/2b0c102b/783/w950h633/20180409/q1WN-fyvtmxe6847322.jpg",
        title:"新青年",
        discription:"拿起画具，向水面滴入颜料，颜料慢慢漾开",
        length:"20集",
        flag:2//代表经典
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/photo/0/w2000h1200/20180322/XJ_G-fysnevk5977709.jpg",
        title:"新青年",
        discription:"佛系夫妇放弃百万年薪在家做艺术皂",
        length:"20集",
        flag:2//代表经典
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/photo/0/w2000h1200/20180322/XJ_G-fysnevk5977709.jpg",
        title:"新青年",
        discription:"拿起画具，向水面滴入颜料，颜料慢慢漾开",
        length:"20集",
        flag:2//代表经典
    },
    {
        id:Math.random()+"1",
        type:1,
        picUrl:"http://n.sinaimg.cn/news/1_img/upload/d2808720/783/w950h633/20180402/gBml-fysuuxz7614821.jpg",
        title:"新青年",
        discription:"出生于1997年的高倩身上有很多标签：“美臀冠军”、“网红主播”、“健身达人”。",
        length:"20集",
        flag:2//代表经典
    },
 ]

 //查询类型;
export const CLASSIFY_TYPES=[
    {
        'types':1,
        'list':[
            {
                'type':1,
                'typeVal':'全部地区',
            },
            {
                'type':2,
                'typeVal':'大陆',
            },
            {
                'type':3,
                'typeVal':'欧美',
            },
            {
                'type':4,
                'typeVal':'日韩',
            },
            {
                'type':5,
                'typeVal':'泰国',
            },
        ]
    },
    {
        'types':2,
        'list':[
            {
                'type':1,
                'typeVal':'全部类型',
            },
            {
                'type':2,
                'typeVal':'古装',
            },
            {
                'type':3,
                'typeVal':'史诗',
            },
            {
                'type':4,
                'typeVal':'科幻',
            },
            {
                'type':5,
                'typeVal':'武侠',
            },
            {
                'type':6,
                'typeVal':'推理',
            },
            {
                'type':7,
                'typeVal':'惊悚',
            },
            {
                'type':8,
                'typeVal':'伦理',
            },
        ]
    },
    {
        'types':3,
        'list':[
            {
                'type':1,
                'typeVal':'不限',
            },
            {
                'type':2,
                'typeVal':'2018',
            },
            {
                'type':3,
                'typeVal':'其他',
            }
        ]
    },
    {
        'types':4,
        'list':[
            {
                'type':1,
                'typeVal':'全部',
            },
            {
                'type':2,
                'typeVal':'打赏',
            },
            {
                'type':3,
                'typeVal':'免费',
            }
        ]
    },
    {
        'types':5,
        'list':[
            {
                'type':1,
                'typeVal':'最多',
            },
            {
                'type':2,
                'typeVal':'最热',
            },
            {
                'type':3,
                'typeVal':'推荐',
            }
        ]
    }
]